### ISSUE TITLE
The intro message is gone

### ISSUE THREAD

**Issue by rockyzhang24** [dstein64/nvim-scrollview#102]
Neovim version: built from the latest commit

To reproduce:
1. make sure `shortmess` option does not contain `I` flag, i.e., add `set shortmess-=I` to `init.vim`
2. run `nvim` in the terminal

The intro message should be shown on the screen forever until any key is pressed. However, the intro message flashed and then disappeared immediately. If I uninstall this plugin, this issue will be resolved. 

https://github.com/dstein64/nvim-scrollview/assets/11582667/73fbfad6-8129-4c07-b011-6d6e7177b244

Thank you.

**Comment by dstein64** [comment]
Thanks for reporting the issue @rockyzhang24.

This is fixed in 06201a265aa57f2099bdeb0f780c5eb92fbd9a55.

The issue started when scrollview initialization was deferred to resolve #99. I didn't notice since my terminal has a white background, for which the intro screen already gets cleared (https://github.com/neovim/neovim/issues/20302).

**Comment by rockyzhang24** [comment]
Cool. Thant you for the quick response. I love this plugin btw, the best scrollbar ever in neovim ecosystem.

**Comment by dstein64** [comment]
Glad to hear you like the plugin!
