### ISSUE TITLE
Error related to Mappings.

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [dstein64/nvim-scrollview#108]
I have recently updated and now this Mappings related error is displayed every time I start Neovim.

![Scrollview_Issue](https://github.com/dstein64/nvim-scrollview/assets/47998118/5e344d2f-cd30-467c-a001-9670e9a6f1f6)

**Comment by dstein64** [comment]
Thanks for letting me know @Fausto-Korpsvart. I believe the problem is the same as the one discussed in #107, an issue I re-opened. Are you still encountering the problem after updating the plugin again? I put an update in 01373406b2c83110b24c6759e0b24bd43d194b33 that I believe will fix the problem.

**Comment by Fausto-Korpsvart** [comment]
> Thanks for letting me know @Fausto-Korpsvart. I believe the problem is the same as the one discussed in #107, an issue I re-opened. Are you still encountering the problem after updating the plugin again? I put an update in [0137340](https://github.com/dstein64/nvim-scrollview/commit/01373406b2c83110b24c6759e0b24bd43d194b33) that I believe will fix the problem.

Actually, before the update everything was fine, but after I updated this day the error started to appear.

I had already read about the error [#107](https://github.com/dstein64/nvim-scrollview/issues/107) and tried the solution, but it didn't work, that's why I opened a new problem.

**Comment by dstein64** [comment]
👍 Glad to hear it's fixed.
