### ISSUE TITLE
Changing `list/nolist` or `listchars` crashes nvim with `trail` sign enabled at startup config

### ISSUE THREAD

**Issue by rosingrind** [dstein64/nvim-scrollview#115]
It seems that changing `list/nolist` option with `nvim-scrollview` is not possible as nvim crashes with no message (just quits). You can only permanently set `list/nolist` in a config. No stderr printed out to the terminal, the return code of `echo $?` is `139`.

If I remove `nvim-scrollview` as a dependency, changing `list/nolist` always succeeds. The return code of `echo $?` after successfully changing this setting and quitting with `:q` is `134`.

## Steps to reproduce

1. Open any file for scrollbar to show up
2. Add trailing spaces
3. Ensure the symbol for trailing space (an outlined square) is drawn near the scrollbar
4. Toggle an option with `:set list` or `:set nolist`

## Configuration (`lazy.nvim`)

```lua
{
    "dstein64/nvim-scrollview",
    opts = {
        signs_on_startup = { "all" },
        column = 1,
        winblend = 0,
    }
}
```

**Comment by dstein64** [comment]
Hi @rosingrind, thanks for reporting the issue. What version of Neovim are you using? Does the issue still arise if you compile Neovim from the latest source code or use a [nightly release](https://github.com/neovim/neovim/releases/tag/nightly)? There was a use-after-free bug that was recently fixed in [Neovim #24289](https://github.com/neovim/neovim/pull/24289) that could cause crashing like you've described. It looks like the fix is planned for `v0.9.2` and `v0.10`.

**Comment by rosingrind** [comment]
Hello @dstein64, thank you for your response! I'm using NVIM v0.9.1, Build type: Release, LuaJIT 2.1.0-beta3.

I've checked it with a nightly release and it seems that everything is working properly within nightly, so you are right about it's a "use-after-free" bug. Seems like this issue may be closed on your demand (idk if you'd like to leave it open to track, or close to clean the clutter).

Thank you for your help and for the plugin!

**Comment by dstein64** [comment]
I was planning on keeping this open, in case others encountered the issue, but I've put in an update (e33e4c0ba5bf8fdde4d4d8011f62f6d72669884a) that seems to work around the problem. Please let me know if that update does not address the issue.
