### ISSUE TITLE
Add support for gitsigns

### ISSUE THREAD

**Issue by Shahabaz-Bagwan** [dstein64/nvim-scrollview#116]
First of all thank you for creating such a useful plugin.

### Feature Request
After using it I feel like the scroll bar should show overview of the document like vscode have. 

### How I am getting that feature right now
To mitigate this I am using it with other plugin "[nvim-scrollbar](https://github.com/petertriho/nvim-scrollbar/tree/main)" irony is the scrollbar plugin shows view of the scroll and scrollview plugin actually implements scrolling :laughing: 

#### My config:
https://github.com/Shahabaz-Bagwan/nvChadCustom/blob/922ab1f5382f2df8d3b3cb8e741f6d878bd65fea/plugins.lua#L153

**Comment by XXiaoA** [comment]
Gitsigns has been supported. Take a look at https://github.com/dstein64/nvim-scrollview/blob/main/lua/scrollview/contrib/gitsigns.lua

**Comment by dstein64** [comment]
@Shahabaz-Bagwan, in addition to the link that @XXiaoA posted, you might also find the following comment helpful:

https://github.com/dstein64/nvim-scrollview/issues/87#issuecomment-1575918307

Because `gitsigns` is not supported as a built-in sign group, it can't be enabled by adding it to `scrollview_signs_on_startup`. Rather, it has to be enabled with:

```lua
require('scrollview.contrib.gitsigns').setup()
```

**Comment by subev** [comment]
@dstein64 Add this to the main README, I almost would have missed adding it.
Great plugin, great work 🙇

**Comment by dstein64** [comment]
Hi @subev, I'm glad to hear you like the plugin. I've added a paragraph to the `README` that mentions the `contrib` plugins (`coc` and `gitsigns`).

https://github.com/dstein64/nvim-scrollview/blob/8e2680557f45aea87465f1b415ee4de1951ee963/README.md?plain=1#L103-L107
