### ISSUE TITLE
Expose the current state in the Lua API

### ISSUE THREAD

**Issue by Granddave** [dstein64/nvim-scrollview#134]
I would like to be able to get the current state (enabled or disabled) to make it possible to store the current state, disable the scrollbar and later restore the previous state. Looks like it would be a simple fix by exposing the `scrollview_enabled` variable in the Lua API.

Thanks for a nice plugin!

**Comment by dstein64** [comment]
Hi @Granddave, I'm glad to hear you like the plugin.

I've added a global variable, `g:scrollview_enabled`, that is set to `v:true` when the plugin is enabled and `v:false` otherwise. This can be accessed from Lua via `vim.g.scrollview_enabled`. The value should be treated as read-only; existing commands can be used for enabling and disabling the plugin (`:ScrollViewEnable`, `:ScrollViewDisable`, and `:ScrollViewToggle`).

Commit: 401c0498689dcaa54b2e7483d823e33cdc051e72
