### ISSUE TITLE
install instructions incompletes

### ISSUE THREAD

**Issue by michaelb** [dstein64/nvim-scrollview#3]
Hi, 
Given  your main branch name is 'main'  instead of the legacy 'master', you should update your install instructions.

For example, with (my up-to-date) vim-plug, I had to do: `Plug 'dstein64/nvim-scrollview', {'branch': 'main'}`
Idk about other plugin managers though, but maybe there are similar updates to make.

Otherwise, very great plugin!

**Comment by dstein64** [comment]
Thanks for reporting this @michaelb!

I've added the branch to the example (85e15471129af1d58f011199a3f41ffc0750e7a6).

I see that vim-plug [Issue #1005](https://github.com/junegunn/vim-plug/issues/1005) was opened to address this, and implemented in [PR #1007](https://github.com/junegunn/vim-plug/pull/1007). The issue was subsequently re-opened, and remains open, to support scenarios where an existing default branch has been renamed.
