### ISSUE TITLE
PlugUpdate failed because doc/tags conflicted

### ISSUE THREAD

**Issue by crispgm** [dstein64/nvim-scrollview#31]
I ran PlugUpdate but failed only on `nvim-scrollview`. And the error messages showed the reason is `git pull` conflict because `doc/tags` changed. I guess delete `doc/tags` would fix this.

**Comment by dstein64** [comment]
Thanks for reporting this @crispgm!

I have included the `tags` file so that e.g., `:help nvim-scrollview` works automatically, without having to first run `:helptags`.

Can you please share the full error message if you still have it?

Have you manually used `:helptags` to generate a `tags` file for `nvim-scrollview`?

**Comment by crispgm** [comment]
> Thanks for reporting this @crispgm!
> 
> I have included the `tags` file so that e.g., `:help nvim-scrollview` works automatically, without having to first run `:helptags`.
> 
> Can you please share the full error message if you still have it?
> 
> Have you manually used `:helptags` to generate a `tags` file for `nvim-scrollview`?

I guess it is because <https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins>.

**Comment by dstein64** [comment]
> "I guess it is because https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins."

It seems like a possibility for the error could be if I didn't keep the `tags` file properly sync'd with `doc/scrollview.txt` and when you updated `nvim-scrollview`, `tags` got locally updated to correspond to the `doc/scrollview.txt` update. Then a later `nvim-scrollview` update that had an update to `tags` couldn't properly run due to a conflict.

I'll create a GitHub Actions workflow that ensures on each commit that `tags` is in sync with `doc/scrollview.txt`. This should prevent the scenario described above that may have caused the conflict you encountered.

**Comment by dstein64** [comment]
> "It seems like a possibility for the error could be if I didn't keep the `tags` file properly sync'd with `doc/scrollview.txt`"

aa8718e1524baef195aacac70a17751eabe55a81 was a recent commit that had an update to `doc/scrollview.txt` without a corresponding update to `tags` that should have been included to drop `flexible` from the `tags` file.

**Comment by dstein64** [comment]
@crispgm, I've added a GitHub Actions check to make sure that `tags` has been properly updated.

I'll port the check to my other Vim/Neovim plugins.

Thanks again!

Please let me know if you encounter a similar issue in the future, since that would suggest that something else is causing the problem.
