### ISSUE TITLE
Scrollbar goes on top of Telescope

### ISSUE THREAD

**Issue by JoseConseco** [dstein64/nvim-scrollview#37]
You can see scrollbar is renderd on to of telescope popu window:
![image](https://user-images.githubusercontent.com/13521338/116010149-a0626f00-a61d-11eb-934d-e0a08860c812.png)
Other than that it works great.

**Comment by dstein64** [comment]
Thanks for reporting this @JoseConseco!

I don't have a solution yet.

I plan to explore whether it's possible to set the precedence of floating windows, similar to the `zindex` property for Vim's popup windows. That way, the scrollbars could have low precedence, which would result in other floating windows appearing above them.

If it's not possible to set floating window precedence, perhaps calling `nvim_win_set_config` causes an existing window to take higher precedence (as if it were a new floating window, assuming new floating windows appear over existing ones). If so, `nvim-scrollview` could call `nvim_win_set_config` on existing floating windows after the scrollbars are shown.

Another possible workaround could be for `nvim-scrollview` to check whether a scrollbar would overlap existing floating windows, and if so, skip displaying that scrollbar.

**Comment by dstein64** [comment]
An unintended side effect of d15b750c584b69f33071239d76ce624c5fe28dc2 is that it's now less likely for scrollbars to cover floating windows. However, a more substantial update is required for a more robust solution.

**Comment by JoseConseco** [comment]
Thank  the update seems to fix the scrollbar rendering on top of telescope popu.

**Comment by dstein64** [comment]
As of 707ef4c3384e9efd4a2fa3e4ca58a50644e80fa8, there is a `scrollview_hide_on_intersect` setting (disabled by default) for hiding scrollbars when they would intersect with floating windows.

I did not find any way to configure the z-index of floating windows. Calling `nvim_win_set_config` on existing windows didn't change their precedence.

I did find that making a floating window active would make its precedence higher than intersecting floating windows, but I could not figure out a way to do this from the plugin script. I tried moving the cursor to the float, followed calling `redraw`, then moving the cursor back to the starting window, but I couldn't get the desired outcome.

I also considered partially hiding a scrollbar when it would intersect with a floating window, but opted not to take this approach due to the complications that would arise, particularly 1) when the overlapping floating window would split the scrollbar into two separate parts and/or 2) from interactions with scrollbar mouse dragging.

I've opened Neovim feature request [#14465](https://github.com/neovim/neovim/issues/14465) requesting the ability to specify z-index. If that functionality is added, `nvim-scrollview` scrollbars can be created with low z-index.

**Comment by JoseConseco** [comment]
I think you have seen this : https://github.com/neovim/neovim/pull/14468 .  But I do not have any problems with ui sorting now

**Comment by dstein64** [comment]
As of 1e6a6954c62f57953cd718ca5ed453321037a193, `nvim-scrollview` now uses a default z-index of 40, which is intentionally lower than the default z-index of 50 that's used for floating windows. This way, `nvim-scrollview` scrollbars will have a lower z-index than other floating windows that use the default value.

**Comment by JoseConseco** [comment]
Thx for the fix. Issue is gone now
