### ISSUE TITLE
False floating detection using coc.nvim

### ISSUE THREAD

**Issue by yutkat** [dstein64/nvim-scrollview#39]
I'm using coc.nvim, and after [this commit](https://github.com/dstein64/nvim-scrollview/commit/4cae22a1db7ae4ebb0eb5c3695ab3ea2cf445c11#diff-a3dae0a8c81f0336af552468db09fc0306a31f24cac711d49598201ca740cdfdR370-R371), the [floating window detection](https://github.com/neoclide/coc.nvim/blob/d3e40ceabd76323c07434fc2711521cc8bb2d028/autoload/coc/float.vim#L646-L649) is not working properly.

## minimal vimrc

```vim
syntax enable
filetype plugin indent on

call plug#begin(stdpath('data') . '/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dstein64/nvim-scrollview'
call plug#end()

" https://github.com/neoclide/coc.nvim/blob/473668eabee0592e817f9c692b0509c2743fb1c3/Readme.md#L217-L222
nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
```

## Steps to reproduce 

1. Open a file that displays scroll bars.
2. split horizontally (`:sp`) <- important this step!  not split and vsplit work well.
3. scroll window `<C-f>`

**Comment by dstein64** [comment]
Thanks for reporting this @yutkat!

I tried using your config along with `coc.nvim` and testing using the steps that you gave. Scrollbars worked as expected, but I'm not sure if non-working scrollbars is the issue you're reporting.

Can you provide more details on 1) "false floating detection" mentioned in the title and 2) the behavior you're observing versus the expected behavior? Any screenshots and/or information on the Neovim version you're using could be helpful.

**Comment by yutkat** [comment]
Thank you for your replay. I apologize for the lack of information.
The versions are as follows
NVIM v0.5.0-dev+1291-gb227cedf8
https://github.com/dstein64/nvim-scrollview/commit/707ef4c3384e9efd4a2fa3e4ca58a50644e80fa8
https://github.com/neoclide/coc.nvim/commit/473668eabee0592e817f9c692b0509c2743fb1c3

And, I took this video. Can you see that this will not scroll?

https://user-images.githubusercontent.com/8683947/116909265-eef7b500-ac7e-11eb-9fa1-1b2033f8b76f.mp4

**Comment by dstein64** [comment]
> "Can you see that this will not scroll?"

That makes the issue clear. Thanks @yutkat!

**Comment by dstein64** [comment]
I've opened https://github.com/neoclide/coc.nvim/pull/3066, which updates `coc.nvim` so that it only considers windows created by `coc.nvim`. Without that update, it appears that the `coc.nvim` scrolling functionality considers all floating windows that can be scrolled, including those created outside the context of that plugin (e.g., `nvim-scrollview` scrollbars).

I've put in a temporary workaround in 57c6534d8faeb8cf1fde3a7e4f056dcecd5b4646 (this will only work if `g:scrollview_character` is not used), which I will revert if https://github.com/neoclide/coc.nvim/pull/3066 is merged.

**Comment by yutkat** [comment]
Thank you very much :smiling_face_with_three_hearts: 
I confirmed that it works with the latest version by not setting g:scrollview_character.

**Comment by dstein64** [comment]
5d18f3e13909e96d3a28a79404d4c558ab193d2c reverts the temporary workaround that was added in 57c6534d8faeb8cf1fde3a7e4f056dcecd5b4646, as it's no longer necessary after the `coc.nvim` update in https://github.com/neoclide/coc.nvim/commit/c126ff423a3556d05c4e2a82920402607b0a22ea.
