### ISSUE TITLE
Not usable in wrap mode

### ISSUE THREAD

**Issue by chriskisskiss** [dstein64/nvim-scrollview#50]
I think scrolling should be calculated on visual lines rather than real lines.
With wrap enabled, the visual feedback is basically gone.

Greetings!

**Comment by dstein64** [comment]
Thanks for filing this @chriskisskiss!

I haven't encountered the issue myself. Can you provide a specific example file that results in the issue, or some set of steps I can use to create a file that results in the issue?

**Comment by chriskisskiss** [comment]
Hi, it basically occurs to all files when :set wrap is enabled and there are long lines.
To exaggerate things, when there are wrapped very long but few lines, the scrollbar indicates no possible scrolling at all.
Independently from the plugin, there seems to be no way to scroll in vim between real lines, e.g. when i use gj gk to navigate between wrapped lines, vim is jumping only real-line wise.
However, maybe there is is a way for you to calculate visual lines and adjust the scrollbar accordingly.

Thanks for your work!

**Comment by dstein64** [comment]
> "Hi, it basically occurs to all files when :set wrap is enabled and there are long lines."

I downloaded `Alice’s Adventures in Wonderland` from https://www.gutenberg.org/files/11/11-0.txt.

The lines were hard wrapped, so I converted the document to have long lines with:

```vim
:%normal! vipJ
```

In this case, the scrollbars appear to work generally as expected with the `wrap` setting on. However, the size of the scrollbars are too large relative to how they would be if calculated how you suggested.

> "With wrap enabled, the visual feedback is basically gone."

Do you have a real example where the issue is prevalent? That could be helpful for devising a solution. If the document has confidential/sensitive data, the data can be redacted with e.g., `:normal! ggVGrX`. For the file I tried above, the visual feedback, while not perfect, works okay.

**Comment by dstein64** [comment]
> "Independently from the plugin, there seems to be no way to scroll in vim between real lines, e.g. when i use gj gk to navigate between wrapped lines, vim is jumping only real-line wise."

When I press `gj`, Neovim navigates down to the later part of a wrapped line. Does this match the behavior you're encountering?


https://user-images.githubusercontent.com/541289/132103196-bd81320f-ea12-49d9-8e7e-6dea41872178.mp4

**Comment by dstein64** [comment]
I can now replicate the issue. Trying with `Alice’s Adventures in Wonderland` did not have a problem because of the length of the document. When I follow the same steps (`:%normal! vipJ`) used [above](https://github.com/dstein64/nvim-scrollview/issues/50#issuecomment-913007222) to create long lines, but then only keep a small number of initial lines (e.g., 40), I encounter the same issue described [above](https://github.com/dstein64/nvim-scrollview/issues/50#issue-988267404).

**Comment by chriskisskiss** [comment]
I really appreciate a lot your help and your work.
The video exactly depicts what I've meant.
I am currently really hard writing on my thesis, in which I encountered this behaviour. Since I don't want to publish the text yet, I didn't have time setting up an alternative text.
I understand that for coding, wrapped lines are rarely used, which is why it probably isn't an issue for most users.
Ather plugins behave exactly the same (e.g. Xuyuanp/scrollbar.nvim) and also GUI implementations of neovim.

Thank you very much.

**Comment by dstein64** [comment]
As of 01fbd97597b33ece9700c178cdde52268cb6f2bc, there's a new scrollview mode, `proper`, that accounts for wrapped lines.

By default, the scrollview mode is set to `auto`, which will account for wrapped lines only when the buffer has relatively few lines (the scenario where the issue is most prevalent).

The plugin can be configured to use `proper` mode in all scenarios, but this mode works slower than the other modes (which could be problematic depending on your hardware and file lengths).

```vim
let g:scrollview_mode = 'proper'
```
