### ISSUE TITLE
Bad z index when using floating windows/popups

### ISSUE THREAD

**Issue by DanielCardonaRojas** [dstein64/nvim-scrollview#60]
I encountered this issue when using a split window and a completion menu.

![image](https://user-images.githubusercontent.com/5472687/145650443-ced66a77-55f5-4a8c-b9a3-ea39c04596e0.png)

**Comment by dstein64** [comment]
Thanks for reporting the issue @DanielCardonaRojas!

The zindex is set to 40 by default, intentionally below the default of 50, so that the scrollbars will go beneath other floating windows that don't specify a zindex.

In case that's not low enough, `scrollview_zindex` can be set accordingly or `scrollview_hide_on_intersect` can be set to `1` to force scrollbars to not show when they would otherwise intersect with other floating windows.

Are you using a plugin to show the completion popup? If so, which plugin?

**Comment by DanielCardonaRojas** [comment]
OK awesome I'll play around with that setting to see if I can workaround the issue. Currently I'm using nvim-cmp

**Comment by dstein64** [comment]
I've replicated the issue reported here. I see that the issue arises from `nvim-cmp` using a zindex of 1 for its documentation floating window. I've opened nvim-cmp [PR #661](https://github.com/hrsh7th/nvim-cmp/pull/661) to change the default zindex to 50, which would provide flexibility for setting a lower zindex for other floating windows.

**Comment by dstein64** [comment]
nvim-cmp [PR #661](https://github.com/hrsh7th/nvim-cmp/pull/661) was merged. @DanielCardonaRojas, after updating `nvim-cmp`, the scrollbars should be below the documentation.
