### ISSUE TITLE
Clears :intro screen on startup

### ISSUE THREAD

**Issue by adrian5** [dstein64/nvim-scrollview#79]
The plugin appears to invariably clear the `:intro` screen unless disabled at startup.

**Comment by dstein64** [comment]
Thanks for reporting the issue @adrian5!

fd616a8 includes a fix.

I originally could not reproduce the issue, since I would never see the `:intro` screen with or without `nvim-scrollview`, but it seems that was from the terminal I was using (reported at https://github.com/neovim/neovim/issues/20302).
