### ISSUE TITLE
How to get a proper win count?

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#83]
Since installing scrollview, I noticed that a few small functions I wrote that include a counting the number of open windows via `vim.fn.winnr("$")` do not work properly anymore, since the scrollbar seems to count as one window.

Is there a straightforward way of getting a "real" window count? If not, I'd have to check for scrollview-availability, and then check for window and buffer height, to determine what the real number of windows is, which feels like unnecessarily many loops to jump through

**Comment by dstein64** [comment]
I've faced this same issue. `winnr('$')` returns the total window count, including floating windows. Since `nvim-scrollview` uses floating windows, it's included in the total window count.

To work around the issue, I've looped over windows, only including them in the count if they are not external and not floating (if they have a `relative` property, they're floating). For example, here's a VimScript example from my `vim-win` plugin.

https://github.com/dstein64/vim-win/blob/069867b9c20f68ed310718fc85148e46810e717b/autoload/win.vim#L31-L49

**Comment by chrisgrieser** [comment]
Thx!

It might be weiterhilft to include this info in the readme, btw 🙂

**Comment by dstein64** [comment]
> "It might be weiterhilft to include this info in the readme, btw 🙂"

As of c0699da2f00976943d39c7b32c015c768f68e74b, I've added the issue under `:help scrollview-issues`. The `README.md` also now refers to that documentation, with the `winnr('$')` issue given as one of the examples.

**Comment by dstein64** [comment]
As of [Neovim #34207](https://github.com/neovim/neovim/pull/34207), `winnr('$')` does not count non-focusable windows. This addresses the issue reported here. The latest version of `nvim-scrollview` is required to properly handle that update (#155).
