### ISSUE TITLE
FR: Add gitsigns as built-in sign group

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#87]
gitsigns should be so useful, that it could make sense to have this as a builtin sign group

**Comment by dstein64** [comment]
The plugin was written so that it would be possible to extend the functionality in a Neovim configuration file or with a plugin.

For example, the following code could be a starting point for a separate plugin with `gitsigns` functionality.
https://gist.github.com/dstein64/b5d9431ebeacae1fb963efc3f2c94cf4

I plan to include a [link](https://github.com/topics/scrollview-signs) in the documentation to repositories tagged with `scrollview-signs` as a GitHub topic.

**Comment by chrisgrieser** [comment]
While I love the idea of making this extensible, I think that gitsigns are such a central use case, that they should be built-in. Right now, it's the only feature which keeps me from switching to this plugin over from [nvim-satellite](https://github.com/lewis6991/satellite.nvim), which otherwise has fewer features and stability than this plugin's implementation

**Comment by dstein64** [comment]
I've added a [contrib](https://github.com/dstein64/nvim-scrollview/tree/main/lua/scrollview/signs/contrib) directory to `nvim-scrollview`.

Within the `contrib` directory is a Lua module that adds `gitsigns` support to `nvim-scrollview`.

The functionality is not added as a built-in, so it's not documented in the plugin documentation and can't be enabled by modifying `scrollview_signs_on_startup`. Rather, it has to be enabled with a Lua function call.
```lua
require('scrollview.signs.contrib.gitsigns').setup()
```

The documentation in [gitsigns.lua](https://github.com/dstein64/nvim-scrollview/blob/main/lua/scrollview/signs/contrib/gitsigns.lua) describes the configuration options.

This seems like a good way to have more of a _batteries included_ approach, without having to increase the maintenance burden of the core project. However, any code in `contrib` may receive less maintenance and have less stability than non-contrib functionality.

**Comment by chrisgrieser** [comment]
thanks you!
