### ISSUE TITLE
Use user-set diagnostic signs by default

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#94]
Currently, when the user has not configured signs for diagnostics, this plugin falls back to `E`, `W`, `H`, and `I`. https://github.com/dstein64/nvim-scrollview/blob/main/plugin/scrollview.vim#L108

However, I think it might make more sense to use any diagnostic icons the user may have already set via `vim.fn.sign_define`.

The user-set values can be retrieved by quering for these:

```lua
require("scrollview").setup {
	diagnostics_error_symbol = vim.fn.sign_getdefined("DiagnosticSignError")[1].text,
	diagnostics_warn_symbol = vim.fn.sign_getdefined("DiagnosticSignWarn")[1].text,
	diagnostics_info_symbol = vim.fn.sign_getdefined("DiagnosticSignInfo")[1].text,
	diagnostics_hint_symbol = vim.fn.sign_getdefined("DiagnosticSignHint")[1].text,
}
```

(I'd make a PR, but the respective file is in vimscript and not lua, in which I am not really knowledgable enough to not mess something up 🙈)

**Comment by dstein64** [comment]
Good idea. Thanks!

If there is user-defined sign text and/or highlights for diagnostics, those will be used by default.

The text is trimmed since I noticed that the manually set text gets padded (e.g., `'E'` gets padded with a trailing space to become `'E '`). If padding is desired, the symbol will have to be set manually.
